### ISSUE TITLE
Packagist is not auto-updating

### ISSUE THREAD

**Issue by geekdevs** [TheBigBrainsCompany/TbbcMoneyBundle#106]
Packagist is not auto-updating anymore to the latest release. This causes the issue of composer not seeing updates.
Probably something's wrong with the hook, could you please check @philippe-levan?

**Comment by philippe-levan** [comment]
Hi @geekdevs,

It seems that there is 3 problems in the composer.json of master branch and 3.x branch :

* the tag name "v4.0.0@beta" is not valid (in the nextcloud project they are naming the beta tags like "v14.0.0beta4" for example. Without the "@")
* the target-dir seems to be removed when we are using psr-4 (it seems that this point is blocking packagist).

I give you below the errors that packagist displaying when I force an update.

I also have something to change in packagist configuration but I can't change it if there is errors in composer.json.

Best regards,
Philippe

```
    Update of tbbc/money-bundle failed, invalid composer.json metadata [Composer\Repository\InvalidRepositoryException] Some branches contained invalid data and were discarded, it is advised to review the log and fix any issues present in branches

    Reading composer.json of tbbc/money-bundle (v4.0.0@beta)
    Skipped tag v4.0.0@beta, invalid tag name

[...]

    Reading composer.json of tbbc/money-bundle (master)
    Importing branch master (dev-master)
    Skipped branch master, Invalid package information: 
    target-dir : this can not be used together with the autoload.psr-4 setting, remove target-dir to upgrade to psr-4

[...]

    Reading composer.json of tbbc/money-bundle (3.x)
    Importing branch 3.x (3.x-dev)
    Skipped branch 3.x, Invalid package information: 
    target-dir : this can not be used together with the autoload.psr-4 setting, remove target-dir to upgrade to psr-4
```

**Comment by geekdevs** [comment]
@philippe-levan ok, that solves it. Thanks for checking.

**Comment by philippe-levan** [comment]
Thanks for the fix.

I made a fix on my side to use the new github hooks.

Best regards,
