### ISSUE TITLE
[Sf4] Stop using ContainerAwareCommands

### ISSUE THREAD

**Issue by althaus** [TheBigBrainsCompany/TbbcMoneyBundle#108]
Hi,

due to changes in Symfony the commands shouldn't access the container directly, but use service injection instead:

> The "Tbbc\MoneyBundle\Command\RatioFetchCommand" class extends "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is deprecated since Symfony 4.2, use {@see Command} instead.
>
> The "Tbbc\MoneyBundle\Command\RatioListCommand" class extends "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is deprecated since Symfony 4.2, use {@see Command} instead.
>
> The "Tbbc\MoneyBundle\Command\RatioSaveCommand" class extends "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" that is deprecated since Symfony 4.2, use {@see Command} instead.

Cheers
Matthias

**Comment by lsv** [comment]
Fixed in #110 
If it gets accepted and merged

**Comment by hanishsingla** [comment]
I don't think this bundle is being managed anymore. @philippe-levan

**Comment by althaus** [comment]
I've switched to my own fork to get it running with Sf4/5. :/

**Comment by hanishsingla** [comment]
Can you share your package with everyone so we can start using your bundle? I think you can register your fork on packagist?

**Comment by geekdevs** [comment]
Thanks for all your contributions guys, sorry I only could only check this now. 
It would be great to start checking Symfony 5 release, any PRs would be appreciated (and checked quickly!).

**Comment by althaus** [comment]
I made some updates in my fork (https://github.com/althaus/TbbcMoneyBundle/releases), but didn't check for BC as I just neeed to get it working again.

**Comment by geekdevs** [comment]
Yes, I saw your fork, making something along same lines. I plan major release so support for some older php and symfony versions will also be dropped.

**Comment by geekdevs** [comment]
This is done and released
