### ISSUE TITLE
SF >4.3 - getCurrencyBundle() is deprecated

### ISSUE THREAD

**Issue by lsv** [TheBigBrainsCompany/TbbcMoneyBundle#119]
"Symfony\Component\Intl\Intl::getCurrencyBundle()" is deprecated since Symfony 4.3, use "Symfony\Component\Intl\Currencies" instead.

**Comment by geekdevs** [comment]
yes, but we need to keep both somehow for BC

**Comment by geekdevs** [comment]
already done
