### ISSUE TITLE
Adding support for symfony 5

### ISSUE THREAD

**Issue by noahlvb** [TheBigBrainsCompany/TbbcMoneyBundle#120]
It seems like there has already been worked on supporting symfony 5. Will it be released anytime soon?

**Comment by geekdevs** [comment]
@noahlvb We've been working on it for some time, but there are still compatibility issues which need to be solved (see travis). If you have time to help with that it would be great!

**Comment by geekdevs** [comment]
Alright, I solved build issues and released v4.0.0 (with Symfony5 support)
