### ISSUE TITLE
Twig widget for SimpleMoneyType is missing

### ISSUE THREAD

**Issue by ostrolucky** [TheBigBrainsCompany/TbbcMoneyBundle#125]
SimpleyMoneyType has [block prefix `tbbc_simple_money`](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/ccad3d13335969e341fdf679cd57a46562f6e8ff/Form/Type/SimpleMoneyType.php#L62), but [no such widget is defined in fields.html.twig](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/master/Resources/views/Form/fields.html.twig).

This results in weird renderings. 
In case of symfony demo application, it shows this
![Screenshot 2020-08-09 at 14 25 20](https://user-images.githubusercontent.com/496233/89732042-29178b80-da4c-11ea-90f0-4db3c23f31e5.png)

And in case of our application, even this
![Screenshot 2020-08-09 at 14 26 56](https://user-images.githubusercontent.com/496233/89732071-62e89200-da4c-11ea-8dcb-ff7b9eb74e08.png)

My expectation is it will show single text field with single label (the one defined as SF stock `label` option in parent form) and currency next to field as a simple text (not pickable).

**Comment by johanwilfer** [comment]
@hanishsingla I am a bit lost with the form implementation (didn't use it myself). Any idea about this one?

**Comment by johanwilfer** [comment]
@ostrolucky Please reopen if this is still an issue, will close this now.
