### ISSUE TITLE
Argument 1 passed to Tbbc\MoneyBundle\Pair\PairManager::setRatioProvider() must implement interface Tbbc\MoneyBundle\Pair\RatioProviderInterface, instance of Exchanger\Service\Chain given

### ISSUE THREAD

**Issue by grekpg** [TheBigBrainsCompany/TbbcMoneyBundle#127]
but one think 

Argument 1 passed to Tbbc\MoneyBundle\Pair\PairManager::setRatioProvider() must implement interface Tbbc\MoneyBundle\Pair\RatioProviderInterface, instance of Exchanger\Service\Chain given

**Comment by TrogWarZ** [comment]
Same here.

Using: php 7.4, symfony 5.2.0 (api-platform 1.3.0), money-bundle 4.0.0, exchanger 2.6.0.

Without exchanger works perfectly. But after adding it like documentation said – this error:
```
 Uncaught Error: Argument 1 passed to Tbbc\MoneyBundle\Pair\PairManager::setRatioProvider() must implement interface Tbbc\MoneyBundle\Pair\RatioProviderInterface, instance of Exchanger\Service\Chain given
```

How to fix?

**Comment by johanwilfer** [comment]
Is this still an issue for you on latest version?

**Comment by hanishsingla** [comment]
@johanwilfer Should we close this issue? Seems outdated now

**Comment by johanwilfer** [comment]
Sounds good @hanishsingla - I don't use the form implementation so tired to ask, but closing as you suggest :)

**Comment by johanwilfer** [comment]
Not sure I follow @trogwarz - you are using another library together with MoneyBundle and seems that is not compatible? There is an ECB implementation in this bundle that I use myself and don't have a problem with, can you try that maybe?
