### ISSUE TITLE
Argument 1 passed to Tbbc\MoneyBundle\Pair\Storage\DoctrineStorage::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of Doctrine\ORM\EntityManager given

### ISSUE THREAD

**Issue by sciro-de** [TheBigBrainsCompany/TbbcMoneyBundle#128]
I found this nice bundle today but I can't seem to get it to work with doctrine. As soon as I set
`tbbc_money:
    storage: doctrine`
I get this TypeError. I don't understand why because when I checked \vendor\tbbc\money-bundle\Pair\Storage\DoctrineStorage.php it seems to be correct to me. Using Symfony 5 with all bundles up to date.

**Comment by Lustmored** [comment]
It seems this bundle still uses old doctrine/common namespace and that's the source of the problem.

**Comment by grekpg** [comment]
fixed

**Comment by johanwilfer** [comment]
This seems to be resolved, will close this issue.
