### ISSUE TITLE
Form error is not showed in input field

### ISSUE THREAD

**Issue by mrcmorales** [TheBigBrainsCompany/TbbcMoneyBundle#130]
Hi,

I'm using this bundle with symfony 4.4 and when I writing some value with mistakes using MoneyType or SimpleMoneyType, the form is caching the error but only showing as general error, not directly in input field.

How Can I resolve it ?

Thank you

**Comment by leegbestand** [comment]
I had the same issue and you can fix it by disabling error bubbling:
```php
            ->add('niet_leden_price', MoneyType::class, ['error_bubbling' => false])
```
