### ISSUE TITLE
Support for Symfony 6 / PHP 8

### ISSUE THREAD

**Issue by lsv** [TheBigBrainsCompany/TbbcMoneyBundle#135]
It seems this is gonna be a big job to fix.

I would properly
- Remove all the non-maintainted PHP (which means only PHP 8.0 and 8.1 should be available) and symfony versions (which means only 4.4, 5.4 and 6.0)
- phpunit/dbunit is not maintained anymore, so that needs to be removed

Maybe even rewrite all the tests, I saw a few classes that isnt loaded in the tests, due to wrong namespace.
And yea, all setUp/tearDown now needs void - because the used phpunit version isnt supported either.

Lot of other methods needs return status (fx console commands).

For this - I would bump the PHP version.

**Comment by lsv** [comment]
Please see PR #136

**Comment by hanishsingla** [comment]
Changes from #136 have been merged in a new v5.0.0-alpha
