### ISSUE TITLE
Doctrine's bundles support

### ISSUE THREAD

**Issue by alvarezmario** [TheBigBrainsCompany/TbbcMoneyBundle#14]
Hi, 
First of all, this is a nice bundle, thanks for sharing. That being said, is so sad it only support the Doctrine ORM. I was hoping to find an open issue here asking for ODM support, but there aren't a single one. 
So I'd like to know if it's on the roadmap to provide support to the entire Doctrine family, the same way the FOS bundles does, because I'd like to use this bundle in my project, but as I'm only using the MongoDBBundle, I can't use it the way it is.
Greetings!

**Comment by geekdevs** [comment]
2.5 years and no interest, not going to happen I guess - closing.
Still if anyone comes with PR for this I would be glad to merge it.
