### ISSUE TITLE
Symfony 7

### ISSUE THREAD

**Issue by althaus** [TheBigBrainsCompany/TbbcMoneyBundle#146]
Hey there,

as Symfony just released a Symfony7-RC1 I've checked my used bundles and TbbcMoneyBundle is one of the bundles missing compatibility yet.

Has anybody started working on this? I guess a proper new release would depend on `^6.4|^7.0`?

Kind regards
Matthias

**Comment by johanwilfer** [comment]
No work in progress yet but PRs are welcome!

**Comment by althaus** [comment]
Thank you, @hanishsingla ♥️
