### ISSUE TITLE
Migrate from Travis to GitHub Actions

### ISSUE THREAD

**Issue by Chris53897** [TheBigBrainsCompany/TbbcMoneyBundle#149]
The ci tests on travis are no longer available. 
https://app.travis-ci.com/TheBigBrainsCompany/TbbcMoneyBundle

GitHub Actions should be used.
If i find some free time, i will have a look

**Comment by johanwilfer** [comment]
Done here: https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/151

Thanks for the PR!
