### ISSUE TITLE
Drop support for PHP 8.0?

### ISSUE THREAD

**Issue by Chris53897** [TheBigBrainsCompany/TbbcMoneyBundle#153]
moneyphp/money dropped the support for PHP 8.0.

Can this be dropped too for this repo?
https://github.com/moneyphp/money/pull/773

**Comment by johanwilfer** [comment]
We need to release 7.0 for this anyway: https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/154
Maybe we can drop support for outdated PHP versions as well.

For reference: https://www.php.net/supported-versions.php
So dropping support for 8.0 sounds good, and support kept for 8.1+
