### ISSUE TITLE
Add Doctrine/ORM 3 support

### ISSUE THREAD

**Issue by Chris53897** [TheBigBrainsCompany/TbbcMoneyBundle#164]
The support for doctrine/orm 3 in require-dev was added in 2022.
https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/commit/d19b40d5073d6bf72f41f4ded323f001052045e8#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R43

Long before it was released 3 weeks ago ;) https://github.com/doctrine/orm/releases/tag/3.0.0

@johanwilfer That is why the Test for the open PRs are failing now.

The only PR ist not failing test is because of removeing support for version 3 https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/162/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R43
Which can be tackled in a seperate PR.

**Comment by Chris53897** [comment]
PHP 8 runs, are useing doctrine/orm 2.18.1 (because of min-version of v3)  That is the reason the tests pass on this runs.

**Comment by johanwilfer** [comment]
Have removed support in this PR as it was clearly mistakenly added: https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/165

But we can use this issue to add it back once we are ready for that.
