### ISSUE TITLE
RFC: Version 6

### ISSUE THREAD

**Issue by Chris53897** [TheBigBrainsCompany/TbbcMoneyBundle#171]
Some ideas for version 6.

- [x] Add doctrine/orm v3 support https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/176
- [x] Drop support for money < 4.4? The update path over version 5 of this bundle should be easy.
- [x] Test on real projects and check it it works as expected
- [x] Add local aware CurrencyType Labels #174
  I guess additional ist the better way. This could be added later.

**Comment by johanwilfer** [comment]
> * Drop support for money < 4.4? The update path over version 5 of this bundle should be easy.

Makes sense, and we can always add it back if it creates issues for people. But removing it has to be done on the major version.

**Comment by johanwilfer** [comment]
We have begun testing this on a real project I am involved in @Chris53897 
About the other things mentioned here do you think they will require backward-incompatible changes? If so we can wait tagging version 6, but if not I am up for releasing 6 after at least our own tests are done. What do you think?

**Comment by Chris53897** [comment]
Thanks for testing. I guess with doctrine/orm 2.x ?The FormField is optional.I am not sure about BC changes to support doctrine/orm 3.Maybe a Release Candidate Version for V3?So more people can test and do not have to use Dev-master.I am on vacation. I will try to find some time after that to have a closer look. But no guarantees.Am 25.03.2024 um 18:40 schrieb Johan Wilfer ***@***.***>:﻿
We have begun testing this on a real project I am involved in @Chris53897
About the other things mentioned here do you think they will require backward-incompatible changes? If so we can wait tagging version 6, but if not I am up for releasing 6 after at least our own tests are done. What do you think?

**Comment by johanwilfer** [comment]
A release candidate looks like a good idea, will start to look into that.

About ORM 2, it is supported at least 2 years: https://www.doctrine-project.org/2024/02/03/doctrine-orm-3-and-dbal-4-released.html so regardless we shouldn't remove support until it is unmaintained..

Will continue testing, enjoy your vacation!

**Comment by Chris53897** [comment]
Thanks.

The only required change has a BC-Layer.
It would be great to have a release candidate for version 6 after #176 is merged.

**Comment by johanwilfer** [comment]
Have tagged 6.0.0 now: https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/releases/tag/v6.0.0

Thanks for all the help! Will close this then.
