### ISSUE TITLE
where is configuration reference ? 

### ISSUE THREAD

**Issue by grekpg** [TheBigBrainsCompany/TbbcMoneyBundle#177]
looking how to setup ratio_file_name and others...

**Comment by johanwilfer** [comment]
See the main readme: https://github.com/TheBigBrainsCompany/TbbcMoneyBundle

If something is missing PRs are welcome explaining it better in that README.
Please reopen in case you think something can be improved (but need more details) or open a PR with your suggestion :)

Thanks!
