### ISSUE TITLE
Twig Filter "spaceless" is deprecated (Since twig/twig 3.12)

### ISSUE THREAD

**Issue by Chris53897** [TheBigBrainsCompany/TbbcMoneyBundle#183]
Since twig/twig 3.12: Twig Filter "spaceless" is deprecated in .../vendor/tbbc/money-bundle/src/Resources/views/Form/fields.html.twig at line 3.

I am not sure what the recommended replacement is.

**Comment by johanwilfer** [comment]
I think an apply tag can be used instead: https://twig.symfony.com/doc/3.x/filters/spaceless.html

Or whitespace control: https://twig.symfony.com/doc/3.x/templates.html#whitespace-control
Not sure if it works exactly as spaceless however..

**Comment by Chris53897** [comment]
Close as completed in https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/186
