### ISSUE TITLE
Doctrine2 Embedded annotation

### ISSUE THREAD

**Issue by voslartomas** [TheBigBrainsCompany/TbbcMoneyBundle#26]
Did you consider to implement Embedded annotation instead of first solution how to persist money in the database?

http://doctrine-orm.readthedocs.org/en/latest/tutorials/embeddables.html

It's just in 2.5.0 branch, which is not stable yet, but it would be imho very nice solution.

**Comment by armetiz** [comment]
Hi @ufik 
As you said; this feature is available on Doctrine 2.5; 
For now, TbbcMoneyBundle could work with Doctrine 2.3.

So, I agree that using the embeddables doctrine feature is a more elegant solution, but this will not work on older project under Doctrine 2.3

@philippe-levan what do you think about this ?

Regards;
Thomas.

**Comment by philippe-levan** [comment]
Hi @ufik,

Yes I believe we have to use this new doctrine feature, perhaps with a new doctrine type. I still didn't look closely at this feature but it is clear it solves a major limitation of this bundle.

We have to keep the backward compatibility. We have to find a way to insert this new doctrine type only when the doctrine version allows to use embedded types.

I'll look at that in february.

Best regards,
Philippe

**Comment by ludofleury** [comment]
I was looking for the same thing. 
So far embeddable are limited (you can't nest them).

Basically it's an embeddable mapping config

```
Money\Money:
    type: embeddable
    fields:
        amount:
            type: bigint
        currency:
            type: currency
```

With a custom type currency.

The thing is I don't see why you want to auto-detect the version of Doctrine. You could introduce this feature as an "extra" document it and if the user has the required version, he could add an option in the bundle config. 

Otherwise, you could detect it in the bundle configuration pass ?

**Comment by ufik** [comment]
@philippe-levan any news fellas?:) It's been more than one year now, I am on new project and facing the same problem. Are you going to implement this, or we should just fork your bundle and implement it?

**Comment by geekdevs** [comment]
Sounds like a nice feature, open for PRs.

**Comment by nspyke** [comment]
Is anyone currently working on a PR for this issue? I'd like to offer my help. I need it for my project as well.

**Comment by nspyke** [comment]
Ok. I'll see what I can do.
Does the code need to support Symfony 2.3 since it's no longer maintained?

**Comment by geekdevs** [comment]
@nspyke Thanks!
no, we support symfony>=2.8

**Comment by geekdevs** [comment]
@nspyke any news on this one yet?

**Comment by nspyke** [comment]
I spent a day working on it without any success. I gave up and implemented it in a couple hours without using this bundle.

**Comment by geekdevs** [comment]
@nspyke could you elaborate what exactly was the problem?

**Comment by geekdevs** [comment]
They are discussing this on `moneyphp/money` project https://github.com/moneyphp/money/issues/328 so we will probably just use their implementation when it's ready.

**Comment by mbrodala** [comment]
@geekdevs Since that issue was closed what is the status here?
