### ISSUE TITLE
SimpleMoneyType Options

### ISSUE THREAD

**Issue by niepi** [TheBigBrainsCompany/TbbcMoneyBundle#27]
Hi, great Bundle.

I have a product which has different fixed prices for different currencies (EUR, USD). I would like to predefine a currency for a form fields and not let the user change the currency.

Thomas.

**Comment by philippe-levan** [comment]
Hi,
I believe the best way is to build your own form type for that. The exact way this form type should work depends on you project.
I'm afraid that a third form type for the same data type (Money) in this bundle would confuse the users.
Best regards,
Philippe
