### ISSUE TITLE
Schema update issue

### ISSUE THREAD

**Issue by MadMind** [TheBigBrainsCompany/TbbcMoneyBundle#31]
Each time I run doctrine:schema:update the type="money" field is updated again and again.
Here is the query:
ALTER TABLE products CHANGE price price VARCHAR(255) NOT NULL;
Here is the field declaration:
    /**
     * @var Money
     * @ORM\Column(name="price", type="money")
     */
    protected $price;

I even upgraded doctrine/orm (v2.4.7 -> v2.5.0) and doctrine/dbal (v2.4.4 -> v2.5.1), same issue.
I do not know where to dig, Tbbc\MoneyBundle\Type\MoneyType::getSqlDeclaration() seems to be OK.

**Comment by johanwilfer** [comment]
@MadMind I just created a PR with a fix. Perhaps you can try it?

**Comment by philippe-levan** [comment]
@johanwilfer thanks for your PR !
