### ISSUE TITLE
Ability to use bundle services independently of reference currency

### ISSUE THREAD

**Issue by sovaalexandr** [TheBigBrainsCompany/TbbcMoneyBundle#32]
This is useful for projects that may not have one main currency or that are multi-currency.
- Ability to specify currency that you are convert from at `PairManager`
- Ability to specify currency different from `reference_currency` at `PairHistoryManager` interactions
- Use `reference_currency` as default currency (for instance if there is no currency to convert from specified)
- Ability to specify rate for currency pair like EUR/USD besides rates that use `reference_currency` as currency from
- Make changes backwards-compatible to use new version of bundle without changing old infrastructure code

**Comment by johanwilfer** [comment]
Sorry for the long delay here @sovaalexandr - I will be closing this issue as it is very old, but feel free to reopen if you still fee it is relevant. PRs are always welcome of course and we can discuss the specifics a bit before if you want but implementation needs to be contributed.
