### ISSUE TITLE
in twig filter: use currency instead of symbol

### ISSUE THREAD

**Issue by wakoch** [TheBigBrainsCompany/TbbcMoneyBundle#34]
I want to output something like 5.000,95 EUR not 5.000,95 €

formatMoney() always uses the currency symbol.

**Comment by JarJak** [comment]
try this:
```
{{ $amount | money_as_float }} {{ $amount | money_get_currency | currency_name }}
```

**Comment by philippe-levan** [comment]
Hi @wakoch,
Sorry for my very late answer.
I believe it is not the role of this bundle to provide any possible output format. The best way is to code your own twig filter to match your need for your application.

The @JarJak hack is a one shot solution if you just have to use it once.

Best regards,
Philippe

**Comment by JarJak** [comment]
I don't agree. This bundle has some predefined filters,  so why not add
another one? I think many people will benefit from having it out of the box
rather than having to reinvent the wheel.
22 sty 2016 14:10 "Philippe Le Van (@plv)" <notifications@github.com>
napisał(a):

**Comment by JarJak** [comment]
I have changed my answer to be more accurate. Now it is:

```
{{ amount | money_format_amount }} {{ $amount | money_get_currency | currency_name }}
```
