### ISSUE TITLE
Documentation states requiring dev-master

### ISSUE THREAD

**Issue by dennisdegreef** [TheBigBrainsCompany/TbbcMoneyBundle#37]
The documentation [README.md](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/master/README.md#installation) states installation is done by performing `composer require tbbc/money-bundle` (which will install a stable version by default) *or* by specifying `dev-master` in your composer.json.

How stable is dev-master? If you'd suggest to use stable releases, you could consider removing the custom composer.json change, or update the documentation with every new release.

**Comment by JarJak** [comment]
+1
