### ISSUE TITLE
Doctrine 2.5: boot() breaks console command(s)

### ISSUE THREAD

**Issue by tomasz-janiczek** [TheBigBrainsCompany/TbbcMoneyBundle#38]
If I do the following:
> app/console doctrine:database:drop --env=prod --force
> app/console doctrine:database:create --env=prod

then

1. first command runs fine
2. second command fails with

> [Doctrine\DBAL\Exception\ConnectionException]                                     
> An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'bv_api'

This is because of the following code:

```php
   public function boot()
    {
        parent::boot();
        
        if($this->container->hasParameter('doctrine.entity_managers')){
            if(!Type::hasType(MoneyType::NAME)) {
                Type::addType(MoneyType::NAME, 'Tbbc\MoneyBundle\Type\MoneyType');
            }

            $entityManagerNameList = $this->container->getParameter('doctrine.entity_managers');
            foreach($entityManagerNameList as $entityManagerName) {
                $em = $this->container->get($entityManagerName);
                if (!$em->getConnection()->getDatabasePlatform()->hasDoctrineTypeMappingFor(MoneyType::NAME)) {
                    $em->getConnection()->getDatabasePlatform()->registerDoctrineTypeMapping(MoneyType::NAME, MoneyType::NAME);
                }
            }
        }
    }
```

The problem is the getDatabasePlatform() call and this issue with Doctrine/DBAL:
http://www.doctrine-project.org/jira/browse/DBAL-1057

Any workaround/fix for this available?
I know it's not the fault of the bundle, but still - would be nice to have something...

**Comment by philippe-levan** [comment]
Hum... right now I don't have any solution. I will ask around me if someone has an idea... If you find a workaround, give me your solution.
Regards,
Philippe

**Comment by Richtermeister** [comment]
I just ran into this as well.

Imho the bundle should not register the types automatically. Adding a type to the project's doctrine configuration is a matter of one line http://symfony.com/doc/current/reference/configuration/doctrine.html#full-default-configuration and I see other bundles take that route as well.

**Comment by rdohms** [comment]
Yep had this as well, either it needs to make itself optional or go the configuration route.

**Comment by glynnforrest** [comment]
See my pull request for a fix: https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/67

**Comment by geekdevs** [comment]
Done in https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/67

This is good for fixing this issue and prevent BC breaks for this version.
However I agree with @Richtermeister, for future major version I think we should remove auto-adding the type and recommend users to add it themselves.
