### ISSUE TITLE
Validation constraint on tbbc_amount

### ISSUE THREAD

**Issue by BboyKeen** [TheBigBrainsCompany/TbbcMoneyBundle#40]
Hi TheBigBrainsCompany !

First of all, thanks for this really useful bundle !

Then, I can't find a way to add a constraint on the amount field so could you provide me any way to do it ?
The only way I'm thinking of is using class constraint but I prefer to avoid it when possible.

Thanks !

**Comment by Swahjak** [comment]
+ 1. I would also like to be able to supply a 'regular' constrain so that I can use jQuery validation to provide client side validation.

**Comment by lsv** [comment]
With #115 if it gets accepted
Its possbile with

```
$builder->add('field', MoneyType::class, [
    'amount_options' => [
          'validation' => '....',
    ],
]);
```
