### ISSUE TITLE
Why does tbbc_money create a table if using csv storage by default?

### ISSUE THREAD

**Issue by lakhman** [TheBigBrainsCompany/TbbcMoneyBundle#42]
I just integrated this into my fresh project, when I run `console doctrine:schema:update --dump-sql`, it wants to create 2 tables to store the ratios. But if by default the storage is `csv` (which it is and does save to `app/data/tbbc_money/ratio_file_name.csv`). Why does it create the tables? (they don't seem to be written to).

```
# config.yml
# TBBC Money Bundle
tbbc_money:
    currencies: ["GBP", "EUR"]
    reference_currency: "GBP"
    decimals: 2
```

```
$ console doctrine:schema:update --dump-sql
CREATE TABLE tbbc_money_doctrine_storage_ratios (id INT AUTO_INCREMENT NOT NULL, currency_code VARCHAR(3) NOT NULL, ratio DOUBLE PRECISION NOT NULL, UNIQUE INDEX UNIQ_1168A609FDA273EC (currency_code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
CREATE TABLE tbbc_money_ratio_history (id INT AUTO_INCREMENT NOT NULL, currency_code VARCHAR(3) NOT NULL, reference_currency_code VARCHAR(3) NOT NULL, ratio DOUBLE PRECISION NOT NULL, saved_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;
```

perhaps it could create the tables only if the the storage is specified as `doctrine`?

also, is there any way to change the location of the csv file? - I couldn't find it in the configuration options. I'd rather save it to the cache directory (it's not important for me if it get's wiped). Is this possible?

**Comment by lakhman** [comment]
### How to set the `ratio_file_name` csv file location:

In your `parameters.yml` add the following:

```
tbbc_money.pair_manager.ratio_file_name: %kernel.root_dir%/data/tbbc_money/ratio-file.csv
```

When you run `console tbbc:money:ratio-fetch` it should save to whatever location you place above.

Perhaps this should be a config option under the bundle? I was looking for the option in `Configuration.php`.

---

#### [Issue] Doctrine tables being created

If I remove the `doctrine` folder from the `config` directory, then it doesn't create the tables, It seems like it's loading the `doctrine` service.

But when I run `console debug:container`, I can't see any doctrine related services under `tbbc`:

```
tbbc_money.form_type.currency                                        Tbbc\MoneyBundle\Form\Type\CurrencyType                                                     
tbbc_money.form_type.money                                           Tbbc\MoneyBundle\Form\Type\MoneyType                                                        
tbbc_money.form_type.simple_money                                    Tbbc\MoneyBundle\Form\Type\SimpleMoneyType                                                  
tbbc_money.formatter.money_formatter                                 Tbbc\MoneyBundle\Formatter\MoneyFormatter                                                   
tbbc_money.money_manager                                             Tbbc\MoneyBundle\Money\MoneyManager                                                         
tbbc_money.pair.csv_storage                                          Tbbc\MoneyBundle\Pair\Storage\CsvStorage                                                    
tbbc_money.pair_manager                                              Tbbc\MoneyBundle\Pair\PairManager                                                           
tbbc_money.ratio_provider.google                                     Tbbc\MoneyBundle\Pair\RatioProvider\GoogleRatioProvider                                     
tbbc_money.ratio_provider.yahoo_finance                              Tbbc\MoneyBundle\Pair\RatioProvider\YahooFinanceRatioProvider                               
tbbc_money.twig.currency                                             Tbbc\MoneyBundle\Twig\Extension\CurrencyExtension                                           
tbbc_money.twig.money                                                Tbbc\MoneyBundle\Twig\Extension\MoneyExtension
```

**Comment by lakhman** [comment]
Figured it out, I had `auto_mapping: true` in my config.yml, so it was automatically loading any entities it could find, instead I changed it to like below and only load the entities from my app (and any others I want), this solves the issue with the database being automatically created.

```
        entity_managers:
            default:
                connection: default
                # this must be false
                auto_mapping: false
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    AppBundle:  ~ # You must specify which bundles you want to load
```

Now no tables are created when using csv (by default), if you wanted to use the tables, I guess you'd have to add the bundle to your mapping (like above) - If you have auto_mapping set to `false`.

up and running! thanks guys!

**Comment by philippe-levan** [comment]
You're welcome :-)
I'm happy that you found the problem. I didn't know where to look for :-)
Regards, Philippe
