### ISSUE TITLE
Symfony 3.0 support?

### ISSUE THREAD

**Issue by drewclauson** [TheBigBrainsCompany/TbbcMoneyBundle#44]
Are there any plans for Symfony 3.0 support or ideas on how hard it would be to get there?

**Comment by drewclauson** [comment]
FYI, I did a quick fork and update of dependencies and it appears to be working with 3.0.  I can issue a PR if you prefer.

**Comment by lakhman** [comment]
There is already a pr here: https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/43

If there's something missing/incorrect specific to symfony 3 please feel free to issue another pr.

**Comment by philippe-levan** [comment]
This PR is already merged, but is reduced to  the sf3 crawler.

I'm interesed by a PR on the SF3 integration. I don't have much time to work on this bundle theses days (weeks?)

Regards, Philippe

**Comment by drewclauson** [comment]
See #45

**Comment by geekdevs** [comment]
Symfony 3 support is now in master
