### ISSUE TITLE
Disabling Doctrine does not prevent from creating tables

### ISSUE THREAD

**Issue by JarJak** [TheBigBrainsCompany/TbbcMoneyBundle#47]
When i disable doctrine:
```
tbbc_money:
    enable_pair_history: true
```
(This stays in documentation; I've tried both true and false, with no luck)

it still tries to create tables with doctrine:schema:update. Is there a way to prevent that?

Another question: how to remove 'tbbc amount' label from form type...

**Comment by geekdevs** [comment]
This is fixed in latest master.
