### ISSUE TITLE
Money v3

### ISSUE THREAD

**Issue by rdohms** [TheBigBrainsCompany/TbbcMoneyBundle#51]
We should start a release for Money v3 now that it is in alpha.

**Comment by mrcmorales** [comment]
+1 

I need a version with Money v3 if not ins 32 bits os I have a overflow in PHP_MAX_INT and not works well to large integers.

Thanks

**Comment by mrcmorales** [comment]
@philippe-levan What do you think? thanks

**Comment by philippe-levan** [comment]
Hi,

Yes we need a v3 version. Look at the PR #45 for this version.

I will create a 2.x branch and master will be the future 3.x release.

I'm waiting for this PR #45 to be ready to merge before doing that.

I will also create an issue to get a new maintainer on this bundle. I don't have any code in SF3.

Best regards,
Philippe

**Comment by geekdevs** [comment]
Since this bundle only uses subset of features from Money library we need to see whether it would be possible to support both v.2 and v.3 without BC breaks (similar to symfony 2.8 and 3.1).

**Comment by philippe-levan** [comment]
The money v3 is a very big change of the money library and some modifications can introduce some major BC Breaks.
The amount is a string in v3 and it is not sortable for example. I'm afraid of an internal amount formatting that can't be sorted with a simple order by.
If we decide ton integrate the money v3 to this bundle, I believe we have to address this issue with amount ordering.
Regards,
Philippe

**Comment by geekdevs** [comment]
@philippe-levan yes, definitely we'd need to look into it in detail and decide if it would be possible to support both versions or we'd need to have a separate version / project for that.

**Comment by geekdevs** [comment]
Started integrating it under https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/tree/feature_money_3 branch. Planning for 4.0 release.

**Comment by geekdevs** [comment]
merged to master
