### ISSUE TITLE
Different values in two servers with same php

### ISSUE THREAD

**Issue by rastydnb** [TheBigBrainsCompany/TbbcMoneyBundle#54]
Hi

we have two server,the two servers have php 5.6.17 , one of server is mi local with nginx ,the other server is production with apache .

When use "add()" function over some moneys, get different result in two servers.

In local we get positive values and no get erros but,
in the producction server get negative values and get this error:

The first parameter of Money must be an integer. It's the amount, expressed in the smallest units of currency (eg cents)

We work with 6 decimals configured in config.yml
We need special php module, or any idea

Thanks

**Comment by geekdevs** [comment]
@rastydnb Sounds like this is not directly related to this bundle as it's not making any calculations. You need to check dependency it's using (https://github.com/moneyphp/money). In particular looks like this is relevant https://github.com/moneyphp/money/issues/40

**Comment by frederikbosch** [comment]
This issue can be closed, was solved [here already](https://github.com/moneyphp/money/issues/172).
