### ISSUE TITLE
Price fields in database keep showing as updated

### ISSUE THREAD

**Issue by aderuwe** [TheBigBrainsCompany/TbbcMoneyBundle#55]
```
$ app/console doctrine:schema:update --dump-sql
ALTER TABLE order_items CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE products CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE product_variants CHANGE price price VARCHAR(255) NOT NULL;

$ app/console doctrine:schema:update --force
Updating database schema...
Database schema updated successfully! "3" queries were executed

$ app/console doctrine:schema:update --dump-sql
ALTER TABLE order_items CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE products CHANGE price price VARCHAR(255) NOT NULL;
ALTER TABLE product_variants CHANGE price price VARCHAR(255) NOT NULL;
```

Any way to avoid this?

**Comment by geekdevs** [comment]
@aderuwe I guess you're using `money` type for storing values? A bit off topic, but I would recommend using 2 fields instead (https://github.com/TheBigBrainsCompany/TbbcMoneyBundle#solution-1--two-fields-in-the-database). In my opinion this is much more flexible solution as it allows you to easily index and search for values.

**Comment by maercky** [comment]
Is there an update on this? 😃

**Comment by mhlavac** [comment]
@aderuwe @maercky for us this got solved when we added comment to database column

in postgres:
```
COMMENT ON COLUMN product.purchase_price IS '(DC2Type:money)';
```

**Comment by mrcmorales** [comment]
hi @aderuwe,

You need to add this option in doctrine configuration:

```doctrine:
    dbal:
        mapping_types:
          money: string```

**Comment by aderuwe** [comment]
@mrcmorales unfortunately, that doesn't seem to do anything here.

**Comment by mrcmorales** [comment]
@aderuwe sorry, I updated my comment, trye now.

**Comment by geekdevs** [comment]
@aderuwe does this solve it for you?

**Comment by aderuwe** [comment]
It did not. I should probably try with latest versions of things, tho...

**Comment by mrcmorales** [comment]
@aderuwe @geekdevs for me is working great this and for different projects, I'm using it with doctrine migrations.

**Comment by geekdevs** [comment]
I cannot reproduce the issue on the latest master. I assume this is doctrine version related.
@aderuwe  Please share your package versions (so that I could add a note about that to README) by running the following:

`composer info | grep "symfony/symfony\|doctrine\|tbbc"`

and

`php -v`

**Comment by geekdevs** [comment]
closing as no further feedback provided. Feel free to re-open with more info if error still occurs.
