### ISSUE TITLE
Consider extracting `PairManager` and related logic to the separate project

### ISSUE THREAD

**Issue by geekdevs** [TheBigBrainsCompany/TbbcMoneyBundle#57]
I truly like how currency fetching/conversion is written in this project, but this is very bound to the bundle. People who don't use symfony cannot benefit from it. I suggest to create a mini-project out of it which would be dealing with currency conversion only (fetching rates, storing etc).

Benefits:
- More people can use it
- More likely to find issues / extend faster
- Current project (TbbcMoneyBundle) would become more lightweight, tests would be running much faster (as there won't be any need to connect to 3rd-party apis). 

I am open to work on this project.

**Comment by geekdevs** [comment]
I've just checked through updates on version 3 of money library and they use this project for the same matter https://github.com/florianv/swap which looks awesome. So, I would suggest to refactor TbbcMoneyBundle to start using it.

**Comment by geekdevs** [comment]
@Baptouuuu Thoughts about this issue? I think this is not bundle-specific logic and we could delegate it to that library instead which supports various providers and would be more flexible. I could work on migrating to it.

**Comment by Baptouuuu** [comment]
I'm always in favour of separating concerns in dedicated libraries. However it will introduce a BC break as the namespaces will change thus enforcing a major release.

@philippe-levan likes to keep BC break as low as possible, so I'm in no position to tell if this separation should be done or not.

**Comment by geekdevs** [comment]
@Baptouuuu I was thinking of keeping the same interface (RatioProviderInterface) and just replace the providers. This should not cause BC in client code

**Comment by geekdevs** [comment]
Working on it under `feature_providers` branch
https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/commits/feature_providers

**Comment by geekdevs** [comment]
This is done, but requires php>=5.5 because of dependencies, so delaying until next major release

**Comment by geekdevs** [comment]
I integrated https://github.com/florianv/exchanger project as an optional dependency for MoneyBundle (both for master and 3.x) versions.
