### ISSUE TITLE
Looking for a maintener for this bundle !

### ISSUE THREAD

**Issue by philippe-levan** [TheBigBrainsCompany/TbbcMoneyBundle#60]
Hi,

You probably noticed that I'm not very reactive on issues and PRs.

I have absolutely no time anymore to maintain this bundle (and I'm not doing so much symfony anymore). So I'm looking for a new maintener for this bundle.

For me, the idea behind this bundle is :
- keep it as simple as possible
- limitate as much as possible BC breaks (and only on major versions)

Is anybody interested in working on this ?

Best regards,
Philippe

**Comment by raistlin** [comment]
My company will use this bundle, I think I could do some mainainment.

**Comment by verschoof** [comment]
@raistlin can you check the PR's already and checkout the issues? For a start to maintain this ;)

**Comment by verschoof** [comment]
@philippe-levan Until you find a new Maintainer, can you please help us to make progress to the Symfony3 version? =)

**Comment by philippe-levan** [comment]
@verschoof Hi, I will create the 2.x branch and merge the PR on a public branch in order to allow anybody to contribute on the v3 version. The master branch will be for the 3.x version.

But right now I have absolutely no time to work on this upgrade...

**Comment by verschoof** [comment]
Hi @philippe-levan, Thanks! Nope, we don't ask you to help to upgrade this =) We only need you for the branches and the PR merges 👍 (I don't mean this harsh btw)

**Comment by raistlin** [comment]
I had to regret, we finally will not use this bundle.

Sorry for any inconvenience.

**Comment by geekdevs** [comment]
@philippe-levan As you could see I've invested quite some time into this project and understand it's internals well. Now, as I have more time for open source projects I'd be glad to become a maintainer. Thanks!

**Comment by philippe-levan** [comment]
@geekdevs oh yeah ! you're a new maintainer !

For me, the idea behind this bundle is
    keep it as simple as possible
    limitate as much as possible BC breaks (and only on major versions)

Thank you for your work on the migration to SF3 and for your future work on this bundle.

I just set you as admin of the bundle.

Do not hesitate to contact me if you have any question.

Best regards,
Philippe

**Comment by geekdevs** [comment]
@philippe-levan Thanks, I appreciate this
