### ISSUE TITLE
symfony3: Could not load type "tbbc_currency" 

### ISSUE THREAD

**Issue by allan-simon** [TheBigBrainsCompany/TbbcMoneyBundle#63]
I'm using the latest version `"reference": "50c9bd4faa2e8e13c29d55aae31609026c92095d"`  (from composer.lock) and I'm getting this error when trying to use a field in a form for a money type
doing 

```php
use Tbbc\MoneyBundle\Form\Type\MoneyType;

class PricingType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('price', MoneyType::class)
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => 'AppBundle\Entity\Pricing',
            ]
        );
    }
}
```

I think it's because `MoneyType` has in its internal definition, that it relies on `tbbc_currency`  for the currency part which does not seem to work aynmore on symfony3

replacing in the code of `MoneyType.php`
the line 
```
            ->setDefaults(array(
               'currency_type' => 'tbbc_currency',
            ))  

```

by

```
            ->setDefaults(array(
               'currency_type' => CurrencyType::class,
            ))  
```

seems to solve the problem (and it's actually put in the possible option , but it's not documented)
Can it be precised at least in the documentation ?

**Comment by geekdevs** [comment]
You are right, this is deprecated definition. Fixed at  https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/65

**Comment by allan-simon** [comment]
thanks for the PR :)

**Comment by geekdevs** [comment]
That PR was merged and should fix it. Closing the issue. 
Feel free to reopen if you have further troubles.
