### ISSUE TITLE
..Entity\DoctrineStorageRatio - not a valid entity or mapped super class

### ISSUE THREAD

**Issue by bubnovKelnik** [TheBigBrainsCompany/TbbcMoneyBundle#70]
v3.1
[Doctrine\ORM\Mapping\MappingException]
Class "Tbbc\MoneyBundle\Entity\DoctrineStorageRatio" is not a valid entity or mapped super class.

**Comment by bubnovKelnik** [comment]
tbbc_money:
    currencies: "%tbbc_money.currencies%"
    reference_currency: "%tbbc_money.reference_currency%"
    decimals: 2
    ratio_provider: tbbc_money.ratio_provider.google
    storage: doctrine
    enable_pair_history: false

**Comment by geekdevs** [comment]
@bubnovKelnik would you please provide more info about your use case? Which code triggers this error?

With `enable_pair_history: false` the bundle should not be initializing or using DoctrineStorageRatio entity.

**Comment by bubnovKelnik** [comment]
Hi!
I do not want to store ratio history, but i want to store current ratio.
With 
enable_pair_history: false 
and 
storage: doctrine
I got this problem - no doctrine mapping config is loaded :(

**Comment by bubnovKelnik** [comment]
This error appears on bin/console tbbc:money:ratio-fetch

**Comment by geekdevs** [comment]
Released fix for this in v3.1.2

**Comment by bubnovKelnik** [comment]
Great!
