### ISSUE TITLE
currency switcher dropdown

### ISSUE THREAD

**Issue by aimeric** [TheBigBrainsCompany/TbbcMoneyBundle#78]
Hi, 

I have install and configure tbbcmoneyBundle and it works fine. I have been searching for a while now and I don't found any way to have a dropdown with twig that I allow the user to switch the currency. In the documentation there is only an example where I can predefined the currency to which I would like my data to be converted to.

` {{ $amount | money_convert("USD") | money_format }}`

Thank you

**Comment by geekdevs** [comment]
There's CurrencyType which could be used to create form with symfony and then render it on twig:

```
 $builder->add('money', \Tbbc\MoneyBundle\Form\Type\CurrencyType::class);
```
