### ISSUE TITLE
Composer update is using old moneyphp and wants getName instead of getCode

### ISSUE THREAD

**Issue by ricardosaracino** [TheBigBrainsCompany/TbbcMoneyBundle#79]
- Removing moneyphp/money (v3.0.2)
  - Installing moneyphp/money (v1.3.0)
    Loading from cache

  - Updating tbbc/money-bundle (v3.1.2 => v3.1.3)
    Checking out 2be1df30df82d7703a13dfddf029cac706e8e9bd

Attempted to call an undefined method named "getCode" of class "Money\Currency".

```
         if (!is_null($taxes)) { 
            $this->taxesAmount = $taxes->getAmount(); 
            $this->taxesCurrency = $taxes->getCurrency()->getCode(); 
        } 
```

https://github.com/moneyphp/money/blob/master/src/Money.php

**Comment by geekdevs** [comment]
@RicardoSaracino money-bundle v.3.x is still using moneyphp v 1.3 which has different notation (`Currency::getName()` instead of `Currency::getCode()`)

see https://github.com/moneyphp/money/blob/1.x/lib/Money/Currency.php

**Comment by RicardoSaracino** [comment]
Any plans on updating this in the near future or will this become an unmaintained project?

**Comment by geekdevs** [comment]
master branch already uses moneyphp v.3, but it is not released and thus unstable.

**Comment by RicardoSaracino** [comment]
cool, im about to release a version of my project. i can look at this for the next iteration then. Much appreciated.

**Comment by hanishsingla** [comment]
Hi. . Any plans on releasing this version. V3.1.4 still using getName() instead of getCode(). https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/v3.1.4/Formatter/MoneyFormatter.php

**Comment by geekdevs** [comment]
@hanishsingla You can use version from `master` for this, but it is considered unstable even though it should work. I don't have much time now so any help with testing that would be great.

**Comment by hanishsingla** [comment]
Sure. . I can also push few Symfony 4 compatibility changes if needed.
