### ISSUE TITLE
www.google.com -> finance.google.com

### ISSUE THREAD

**Issue by Aleg-1990** [TheBigBrainsCompany/TbbcMoneyBundle#83]
Please, change `www.google.com` to `finance.google.com` in [provider](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/master/Pair/RatioProvider/GoogleRatioProvider.php) and docs. This is breaks currency fetching.

**Comment by geekdevs** [comment]
Fixed via https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/commit/e635c700cb851bcdf7ee3a80e537103ee6bb774c
