### ISSUE TITLE
Patch version upgrade from 3.1.3 to 3.1.4 is a big BC break

### ISSUE THREAD

**Issue by glynnforrest** [TheBigBrainsCompany/TbbcMoneyBundle#86]
The 3.1.3 tag requires `moneyphp/money: ^1.2.1`, but 3.1.4 requires `moneyphp/money: ^3.0`.

I'd expect this sort of BC break in a major version bump, not in a patch version upgrade.

I've noticed you've added the `change-log-4.0.md` file, did you intend for this change to happen in the 4.0 release?

**Comment by enekochan** [comment]
I agree. `moneyphp/money: ^3.0` removed some deprecations (for example the use of `Currency::getName`) and all my app broke. I had to lock TbbcMoneyBundle to 3.1.3 for now.

Ref: https://github.com/moneyphp/money/blob/4b18610d3fa0fb0db8fa10b88003ec6028824fe5/CHANGELOG.md#removed

**Comment by geekdevs** [comment]
Thanks, guys - wrong version was released. Master was released which was meant to be version 4.0. I re-released it from 3.x branch as 3.1.4 now

**Comment by glynnforrest** [comment]
Thanks @geekdevs !
