### ISSUE TITLE
CurrencyType uses tbbc_name but should use tbbc_code in 4.0?

### ISSUE THREAD

**Issue by enekochan** [TheBigBrainsCompany/TbbcMoneyBundle#87]
As the bundle is preparing for v4.0 in master branch, it has started using `moneyphp/money` v3.0 which changes how we access the currency in a Money instance from `getName` to `getCode`. The forms in TbbcMoneyBundle still generate CurrencyType with `tbbc_name`, should it have to be changed to `tbbc_code` so it follows the same convention as the `moneyphp/money` library version it's using? This would be a BC break but it also is in `moneyphp/money` v3.0.

**Comment by geekdevs** [comment]
@enekochan I am actually thinking of refactoring this form type. I don't see why would you need additional element there as CurrencyType could be element by itself.

**Comment by enekochan** [comment]
No I don't mean an additional element, just that the CurrencyType when printed with Twig in a form uses as the input name `tbbt_name` which was the accessor method (`getName()`) in `moneyphp/money` in v1.x, but now that TbbcMoneyBundle uses v3.x and the accessor is `getCode()`.

For example now it prints something like this:

```html
<select name="form[price][tbbc_currency][tbbc_name]" id="form_price_tbbc_currency_tbbc_name">
    <option value="EUR" selected="selected">EUR</option>
    <option value="USD">USD</option>
</select>
```

But may be it should print this:

```html
<select name="form[price][tbbc_currency][tbbc_code]" id="form_price_tbbc_currency_tbbc_code">
    <option value="EUR" selected="selected">EUR</option>
    <option value="USD">USD</option>
</select>
```

You can see where this is done here (among other places):

https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/master/Form/Type/CurrencyType.php#L41

**Comment by rpac-tump** [comment]
I first install this bundle the 15th december. I updated today 07th feb. 2018 via composer ("tbbc/money-bundle": "^3.1").
In the doc page for entity definition [see here](https://github.com/TheBigBrainsCompany/TbbcMoneyBundle#saving-money-with-doctrine) we have : 
 public function setPrice(Money $price)
{
  ...
  $this->priceCurrency = $price->getCurrency()->getCode();
  ...
Give an error : Attempted to call an undefined method named "getCode" of class "Money\Currency".
Should be now
  $this->priceCurrency = $price->getCurrency()->getName();

**Comment by enekochan** [comment]
@rpac-tump TbbcMoneyBundle ^3.1 is still using moneyphp/money ^1.2.1:

https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/blob/v3.1.4/composer.json#L21

You have to use dev-master of TbbcMoneyBundle for moneyphp/money ^3.0

**Comment by rpac-tump** [comment]
I look at my version : it's v3.1.4

**Comment by geekdevs** [comment]
@enekochan What I mean is I think it would make sense to have `form[price][tbbc_currency]` as a name (thus avoiding extra form type which is not necessary IMO).

@rpac-tump If you're using v.3 you should be checking according branch, not master:
https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/tree/3.x

**Comment by enekochan** [comment]
@geekdevs Now I understand what you mean :) May be that could make sense but I can't contribute with a valuable opinion on such an important decision. Will be paying attention on v4 release.
