### ISSUE TITLE
Services declared as private won't be able to be obtained from the container in Symfony 4.0

### ISSUE THREAD

**Issue by enekochan** [TheBigBrainsCompany/TbbcMoneyBundle#93]
While looking for deprecations in the process to upgrade my Symfony app from 3.4 to 4.0 I've seen this one:

```
The "tbbc_money.formatter.money_formatter" service is private,
getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0.
You should either make the service public, or stop using the container directly
and use dependency injection instead.
```

Looks like some services are not defined as public and thus won't be able to be obtainer from the container. Those are the services I think should be declared public AFAIK:

- `tbbc_money.pair.csv_storage`
- `tbbc_money.ratio_provider.yahoo_finance`
- `tbbc_money.ratio_provider.google`
- `tbbc_money.formatter.money_formatter`

¿Should those services be declared public? I can provide a PR if needed.

**Comment by geekdevs** [comment]
@enekochan yes, please create PR

**Comment by enekochan** [comment]
Done in #94
