### ISSUE TITLE
Hide decimals if 0 in twig

### ISSUE THREAD

**Issue by danielchodusov** [TheBigBrainsCompany/TbbcMoneyBundle#96]
Hello,

is there any way how to display formatted price like

100 EUR instead of 100.00 EUR in Twig? So decimals are only visible if there are any.

{{ product.price|money_format }}

**Comment by patrickvale** [comment]
I would also like to be able to do this. So far I have come up with a workaround:

`{{ result.priceData.money | money_as_float | number_format }}`

Which isn't ideal but it does at least allow me to keep the money data saved as a Money object, and then control the output (number of decimals, basically, is my requirement).

So in my use case, I have users entering prices, but in some situations (eg search results where I want people to be able to scan the results quickly), I want to reduce the precision - so even is someone enters a price of £1,800.74 I want it to just display £1,800.

I haven't considered rounding at this point - but that might be a useful option.

**Comment by Wirone** [comment]
I thought that setting `decimals: 0` would fix it but unfortunately it causes more problems - `Money::EUR('2900')` rendered in Twig using `money|money_localized_format` prints `$2,900`.

Currently I ended up with `money|money_as_float|format_currency(money.currency.code, { fraction_digit: 0 })` which uses [`format_currency`](https://twig.symfony.com/doc/3.x/filters/format_currency.html) from `twig/intl-extra`.

But it would be great it this bundle could support formatting rounded amount with currency in intl format.

**Comment by johanwilfer** [comment]
How would you suggest this worked if this was implemented?

**Comment by johanwilfer** [comment]
Closing this now, please reopen if this is still relevant.
